[project]
name = "dwa-demo"
version = "0.1.0"
description = "Dynamic Window Approach Trajectory Planner"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gif[plotly]==3.0.0",
    "numpy>=2.3.2",
    "plotly>=6.3.0",
    "pytest>=8.4.1",
]
